---
apiVersion: v1
kind: Namespace
metadata:
  name: dese
---
apiVersion: v1
kind: Namespace
metadata:
  name: homo
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: devops