---
apiVersion: v1
kind: Service
metadata:
  name: py-fs
  labels:
    name: py-fs-nodeport-svc
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 30180
      name: http
    - port: 443
      nodePort: 31443
      name: https
  selector:
    name: py-fs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-fs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: py-fs
  template:
    metadata:
      labels:
        name: py-fs
    spec:
      containers:
      - name: py-fs-container
        image: rogeriosilvarocha/py-fs:0.1
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "mssql+pymssql://SA:Password12@py-db:1433/"
        ports:
        - containerPort: 5000
        - containerPort: 443
      restartPolicy: Always  