apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-fs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: py-fs
  template:
    metadata:
      labels:
        name: py-fs
    spec:
      containers:
      - name: py-fs-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        - containerPort: 443