---
apiVersion: v1
kind: Service
metadata:
  name: py-db
  labels:
    name: py-db-nodeport-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: http
  selector:
    name: py-db 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: py-db
  template:
    metadata:
      labels:
        name: py-db
    spec:
      containers:
        - name: py-db-container
          image: postgres:9.6
          securityContext:
            runAsUser: 0
          env:
          - name: POSTGRES_PASSWORD
            value: "Password12"
          - name: ACCEPT_EULA
            value: "Y"
          ports:
          - containerPort: 5432
          volumeMounts:
          - mountPath: /var/lib/postgresql/data 
            name: fs-data
      volumes: 
        - name: fs-data
          persistentVolumeClaim:
            claimName: pvc-fs-data
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: fs-data
  labels:
    type: local
spec:
  storageClassName: manual-for-fs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/rpsr/fs-pg-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-fs-data
  namespace: default
spec:
  storageClassName: manual-for-fs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi